---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  client_rb:
    environment: _default
  attributes:
    apt:
      compile_time_update: true
    openssh:
      server:
        password_authentication: 'yes'
        permit_root_login: 'yes'
    ntp:
      apparmor_enabled: false
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true
    platformstack:
      iptables:
        allow_ssh_from_world: true
      cloud_monitoring:
        enabled: false
      cloud_backup:
        enabled: false
      omnibus_updater:
        enabled: false

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: centos-6.6
    run_list:
    - recipe[yum]

suites:
  - name: default
    run_list:
      - recipe[rackspace_cloudbackup::cloud]
    attributes:
      rackspace_cloudbackup:
        mock: true
        backups:
          - location: /etc
            enabled: false
          - location: /home
            enabled: false
        backups_defaults:
          cloud_notify_email: root@localhost
      rackspace:
        datacenter: 'DFW'
        cloud_credentials:
          username: nobody
          api_key:  secret
